warning: /bin/sh: setlocale: LC_ALL: cannot change locale (C.UTF-8)
pluginManagement { repositories { google(); mavenCentral(); gradlePluginPortal() } }
dependencyResolutionManagement { repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS); repositories { google(); mavenCentral() } }
rootProject.name = "ContentTransfer"
include ':app'
