package ink.yode.contenttransfer;

import android.content.*;
import android.database.Cursor;
import android.database.sqlite.*;
import android.net.Uri;
import org.json.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicBoolean;

/** Durable per-server cache and outbox. Payloads are JSON to keep migrations small and lossless. */
final class SyncDatabase extends SQLiteOpenHelper {
    static final String SYNCED="synced", PENDING="pending", SYNCING="syncing", CONFLICT="conflict";
    static final class Operation { String id,itemId,type,payload; long baseRevision,createdAt; int attempts; }
    static final class PendingUpload { String id,server,path,name,expiry; int attempts; }
    private static final AtomicBoolean OPERATIONS_DRAINING=new AtomicBoolean();
    private static final Set<String> UPLOADS_IN_FLIGHT=Collections.newSetFromMap(new ConcurrentHashMap<>());
    static boolean beginOperations(){return OPERATIONS_DRAINING.compareAndSet(false,true);}static void endOperations(){OPERATIONS_DRAINING.set(false);}
    static boolean beginUpload(String id){return UPLOADS_IN_FLIGHT.add(id);}static void endUpload(String id){UPLOADS_IN_FLIGHT.remove(id);}
    SyncDatabase(Context context){super(context,"content-sync.db",null,2);}
    @Override public void onCreate(SQLiteDatabase db){
        db.execSQL("CREATE TABLE items(server TEXT NOT NULL,id TEXT NOT NULL,json TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 0,sync_state TEXT NOT NULL DEFAULT 'synced',conflict_json TEXT,PRIMARY KEY(server,id))");
        db.execSQL("CREATE TABLE pending_operations(operation_id TEXT PRIMARY KEY,server TEXT NOT NULL,item_id TEXT NOT NULL,type TEXT NOT NULL,payload_json TEXT NOT NULL,base_revision INTEGER NOT NULL,created_at INTEGER NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,last_error TEXT)");
        db.execSQL("CREATE INDEX pending_server_created ON pending_operations(server,created_at)");
        createUploads(db);
    }
    private void createUploads(SQLiteDatabase db){db.execSQL("CREATE TABLE IF NOT EXISTS pending_uploads(upload_id TEXT PRIMARY KEY,server TEXT NOT NULL,path TEXT NOT NULL,name TEXT NOT NULL,expiry TEXT NOT NULL,created_at INTEGER NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,last_error TEXT)");db.execSQL("CREATE INDEX IF NOT EXISTS uploads_server_created ON pending_uploads(server,created_at)");}
    @Override public void onUpgrade(SQLiteDatabase db,int oldVersion,int newVersion){if(oldVersion<2)createUploads(db);}
    synchronized JSONArray load(String server)throws JSONException {JSONArray out=new JSONArray();try(Cursor c=getReadableDatabase().rawQuery("SELECT json,sync_state,conflict_json FROM items WHERE server=? ORDER BY rowid",new String[]{server})){while(c.moveToNext()){JSONObject o=new JSONObject(c.getString(0));String state=c.getString(1);if(o.optBoolean("localDeleted")&&!CONFLICT.equals(state))continue;o.put("syncState",state);if(!c.isNull(2))o.put("conflict",new JSONObject(c.getString(2)));out.put(o);}}return out;}
    synchronized void replaceRemote(String server,JSONArray remote)throws JSONException {SQLiteDatabase db=getWritableDatabase();db.beginTransaction();try{
        HashSet<String> protectedIds=new HashSet<>();try(Cursor c=db.rawQuery("SELECT item_id FROM pending_operations WHERE server=?",new String[]{server})){while(c.moveToNext())protectedIds.add(c.getString(0));}
        try(Cursor c=db.rawQuery("SELECT id FROM items WHERE server=?",new String[]{server})){while(c.moveToNext())if(!protectedIds.contains(c.getString(0)))db.delete("items","server=? AND id=?",new String[]{server,c.getString(0)});}
        for(int n=0;n<remote.length();n++){JSONObject o=remote.getJSONObject(n);String id=o.getString("id");if(protectedIds.contains(id))continue;putItem(db,server,o,SYNCED,null);}
        db.setTransactionSuccessful();}finally{db.endTransaction();}}
    synchronized void putLocal(String server,JSONObject item,String state)throws JSONException {putItem(getWritableDatabase(),server,item,state,null);}
    private void putItem(SQLiteDatabase db,String server,JSONObject item,String state,String conflict)throws JSONException {ContentValues v=new ContentValues();v.put("server",server);v.put("id",item.getString("id"));v.put("json",item.toString());v.put("revision",item.optLong("revision"));v.put("sync_state",state);v.put("conflict_json",conflict);db.insertWithOnConflict("items",null,v,SQLiteDatabase.CONFLICT_REPLACE);}
    synchronized void removeLocal(String server,String id){getWritableDatabase().delete("items","server=? AND id=?",new String[]{server,id});}
    synchronized boolean hasPending(String server,String id){try(Cursor c=getReadableDatabase().rawQuery("SELECT 1 FROM pending_operations WHERE server=? AND item_id=? LIMIT 1",new String[]{server,id})){return c.moveToFirst();}}
    synchronized void applyRemote(String server,String oldId,JSONObject item)throws JSONException {if(hasPending(server,oldId)||hasPending(server,item.getString("id")))return;SQLiteDatabase db=getWritableDatabase();db.delete("items","server=? AND id=?",new String[]{server,oldId});putItem(db,server,item,SYNCED,null);}
    synchronized void applyDelete(String server,String id){if(!hasPending(server,id))removeLocal(server,id);}
    synchronized String enqueue(String server,String itemId,String type,JSONObject payload,long baseRevision)throws JSONException {String operationId=UUID.randomUUID().toString();ContentValues v=new ContentValues();v.put("operation_id",operationId);v.put("server",server);v.put("item_id",itemId);v.put("type",type);v.put("payload_json",payload.toString());v.put("base_revision",baseRevision);v.put("created_at",System.currentTimeMillis());getWritableDatabase().insertOrThrow("pending_operations",null,v);return operationId;}
    synchronized Operation next(String server){try(Cursor c=getReadableDatabase().rawQuery("SELECT operation_id,item_id,type,payload_json,base_revision,created_at,attempts FROM pending_operations WHERE server=? ORDER BY created_at LIMIT 1",new String[]{server})){if(!c.moveToFirst())return null;Operation o=new Operation();o.id=c.getString(0);o.itemId=c.getString(1);o.type=c.getString(2);o.payload=c.getString(3);o.baseRevision=c.getLong(4);o.createdAt=c.getLong(5);o.attempts=c.getInt(6);return o;}}
    synchronized boolean hasOperations(String server){try(Cursor c=getReadableDatabase().rawQuery("SELECT 1 FROM pending_operations WHERE server=? LIMIT 1",new String[]{server})){return c.moveToFirst();}}
    synchronized boolean hasConflicts(String server){try(Cursor c=getReadableDatabase().rawQuery("SELECT 1 FROM items WHERE server=? AND sync_state=? LIMIT 1",new String[]{server,CONFLICT})){return c.moveToFirst();}}
    synchronized void syncing(String server,String id){state(server,id,SYNCING,null);}
    synchronized void complete(String operationId,String server,String oldId,JSONObject serverItem)throws JSONException {SQLiteDatabase db=getWritableDatabase();db.beginTransaction();try{db.delete("pending_operations","operation_id=?",new String[]{operationId});if(serverItem!=null){String newId=serverItem.getString("id");db.delete("items","server=? AND id=?",new String[]{server,oldId});putItem(db,server,serverItem,hasPending(server,oldId)?PENDING:SYNCED,null);remapPending(db,server,oldId,newId,serverItem.optLong("revision"));}else db.delete("items","server=? AND id=?",new String[]{server,oldId});db.setTransactionSuccessful();}finally{db.endTransaction();}}
    private void remapPending(SQLiteDatabase db,String server,String oldId,String newId,long revision)throws JSONException {ArrayList<String> ids=new ArrayList<>(),payloads=new ArrayList<>();try(Cursor c=db.rawQuery("SELECT operation_id,payload_json FROM pending_operations WHERE server=? AND item_id=? ORDER BY created_at",new String[]{server,oldId})){while(c.moveToNext()){ids.add(c.getString(0));payloads.add(c.getString(1));}}for(int n=0;n<ids.size();n++){JSONObject p=new JSONObject(payloads.get(n));String type="";try(Cursor c=db.rawQuery("SELECT type FROM pending_operations WHERE operation_id=?",new String[]{ids.get(n)})){if(c.moveToFirst())type=c.getString(0);}String endpoint=type.equals("favorite")?"/favorite/":type.equals("edit")?"/edit/":type.equals("rename")?"/rename/":type.equals("delete")?"/delete/":"";if(!endpoint.isEmpty())p.put("endpoint",endpoint+Uri.encode(newId,"/"));ContentValues v=new ContentValues();v.put("item_id",newId);v.put("payload_json",p.toString());if(n==0)v.put("base_revision",revision);db.update("pending_operations",v,"operation_id=?",new String[]{ids.get(n)});}}
    synchronized void retry(String operationId,String error){ContentValues v=new ContentValues();v.put("last_error",error);getWritableDatabase().execSQL("UPDATE pending_operations SET attempts=attempts+1,last_error=? WHERE operation_id=?",new Object[]{error,operationId});}
    synchronized void conflict(String operationId,String server,String id,JSONObject remote){String detail="{}";try(Cursor c=getReadableDatabase().rawQuery("SELECT type,payload_json FROM pending_operations WHERE operation_id=?",new String[]{operationId})){if(c.moveToFirst()){JSONObject x=new JSONObject();x.put("type",c.getString(0));x.put("payload",new JSONObject(c.getString(1)));x.put("remote",remote==null?JSONObject.NULL:remote);detail=x.toString();}}catch(Exception ignored){}SQLiteDatabase db=getWritableDatabase();db.delete("pending_operations","operation_id=?",new String[]{operationId});ContentValues v=new ContentValues();v.put("sync_state",CONFLICT);v.put("conflict_json",detail);int changed=db.update("items",v,"server=? AND id=?",new String[]{server,id});if(changed==0&&remote!=null)try{putItem(db,server,remote,CONFLICT,detail);}catch(Exception ignored){}}
    synchronized void state(String server,String id,String state,String conflict){ContentValues v=new ContentValues();v.put("sync_state",state);v.put("conflict_json",conflict);getWritableDatabase().update("items",v,"server=? AND id=?",new String[]{server,id});}
    synchronized PendingUpload addUpload(String server,String path,String name,String expiry){PendingUpload u=new PendingUpload();u.id=UUID.randomUUID().toString();u.server=server;u.path=path;u.name=name;u.expiry=expiry;ContentValues v=new ContentValues();v.put("upload_id",u.id);v.put("server",server);v.put("path",path);v.put("name",name);v.put("expiry",expiry);v.put("created_at",System.currentTimeMillis());getWritableDatabase().insertOrThrow("pending_uploads",null,v);return u;}
    synchronized ArrayList<PendingUpload> uploads(String server){ArrayList<PendingUpload> out=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT upload_id,server,path,name,expiry,attempts FROM pending_uploads WHERE server=? ORDER BY created_at",new String[]{server})){while(c.moveToNext()){PendingUpload u=new PendingUpload();u.id=c.getString(0);u.server=c.getString(1);u.path=c.getString(2);u.name=c.getString(3);u.expiry=c.getString(4);u.attempts=c.getInt(5);out.add(u);}}return out;}
    synchronized void uploadComplete(String id){getWritableDatabase().delete("pending_uploads","upload_id=?",new String[]{id});}
    synchronized void uploadFailed(String id,String error){getWritableDatabase().execSQL("UPDATE pending_uploads SET attempts=attempts+1,last_error=? WHERE upload_id=?",new Object[]{error,id});}
    synchronized ArrayList<String> pendingServers(){ArrayList<String> out=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT server FROM pending_operations UNION SELECT server FROM pending_uploads",null)){while(c.moveToNext())out.add(c.getString(0));}return out;}
}
